name: Build and Run Dividend Trader

on:
  push:
    branches:
      - main
  schedule:
    # Account for daylight savings
    - cron: '30 14 * 11,12,1,2,3 *' # Nov to Mar
    - cron: '30 13 * 4,5,6,7,8,9,10 *' # Mar to Nov
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/thesiggs/dividends-trader:latest

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Github Container Registry
        run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME .
      - name: Push Docker image
        run: docker push $IMAGE_NAME
      - name: Logout of Github Container Registry
        run: docker logout ghcr.io

  run:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
      ALPACA_API_SECRET: ${{ secrets.ALPACA_API_SECRET }}
      POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
    steps:
      - name: Login to Github Container Registry
        run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Pull Docker image
        run: docker pull $IMAGE_NAME
      - name: Run docker container
        run: docker run $IMAGE_NAME
      - name: Logout of Github Container Registry
        run: docker logout ghcr.io


      
