name: Build and Run Trader

on:
  push:
    branches:
      - main
  schedule:
    # Account for daylight savings
    - cron: '30 14 * 11,12,1,2,3 *' # Nov to Mar
    - cron: '30 13 * 4,5,6,7,8,9,10 *' # Mar to Nov
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/thesiggs/dividends-trader:latest

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME .
      - name: Push Docker image
        run: docker push $IMAGE_NAME
      - name: Logout of Github Container Registry
        run: docker logout ghcr.io

  ExdividendShorter:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Pull Docker image
        run: docker pull $IMAGE_NAME
      - name: Run docker container
        run: docker run -e ALPACA_API_KEY=${{ secrets.ALPACA_API_KEY_PA31SXB8FOAV }} -e ALPACA_API_SECRET=${{ secrets.ALPACA_API_SECRET_PA31SXB8FOAV }} -e POLYGON_API_KEY=${{ secrets.POLYGON_API_KEY }} -e ENV=${{ vars.ENV }} $IMAGE_NAME
      - name: Logout of Github Container Registry
        run: docker logout ghcr.io

  DividendFlipper:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Pull Docker image
        run: docker pull $IMAGE_NAME
      - name: Run docker container
        run: docker run -e ALPACA_API_KEY=${{ secrets.ALPACA_API_KEY_PA3EZ2WN3OEZ }} -e ALPACA_API_SECRET=${{ secrets.ALPACA_API_SECRET_PA3EZ2WN3OEZ }} -e POLYGON_API_KEY=${{ secrets.POLYGON_API_KEY }} -e ENV=${{ vars.ENV }} $IMAGE_NAME
      - name: Logout of Github Container Registry
        run: docker logout ghcr.io
