name: Build and Run Dividend Trader

on:
  push:
    branches:
      - main
  schedule:
    # Account for daylight savings
    - cron: '30 14 * 11,12,1,2,3 *' # Nov to Mar
    - cron: '30 13 * 4,5,6,7,8,9,10 *' # Mar to Nov

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Github Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository }}:latest .
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:latest

  run:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Github Container Registry
        run: echo ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Pull Docker image
        run: docker pull ghcr.io/${{ github.repository }}:latest
      - name: Run docker container
        run: docker run -d ghcr.io/${{ github.repositry }}:latest

      
